{
 "title": "SepMon",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value,time FROM disk_usage ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  { "title": "PUMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pump AC State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value,time FROM pump_ac_state ORDER BY time DESC limit 1;"
    }
   ]
  },
  {
   "title": "Pump Amperage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM pump_amperage\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "title": "TANK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Tank Level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value,time FROM tank_level ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Tank Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM tank_level\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}