{
 "title": "SEPMON",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pico Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sepmon_pressure_sensor_temperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Water Level",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sepmon_pressure_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Level (cm)",
   "type": "timeseries",
   "description": "pico pressure sensor",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sepmon_pressure_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pump Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max_over_time(sepmon_pump_current[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pump Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "sepmon_pump_power", "legendFormat": "__auto" }
   ]
  }
 ]
}